/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?*/

function isPentagonal(n) {
  var tmp = (Math.sqrt(1 + 24 * n) + 1) / 6;
  return Number.isInteger(tmp);
}

function pentagonaly(n) {
  return n * (3 * n - 1) / 2;
}

var i = 1;

while(true) {
  var tmp = pentagonaly(i);
  for (var j = i - 1;j > 0;j--) {
    var tmpj = pentagonaly(j);
    if (isPentagonal(tmp - tmpj) && isPentagonal(tmp + tmpj)) {
      console.log(i, j, tmp, tmpj, tmp - tmpj);
      return
    }
  }
  i++;
}
